version: "2"

services:
  chirper:
    container_name: chirper
    build: ./chirper_demo
    tty: true
    volumes:
      - "./chirper_demo/chirper:/chirper"
      - "/chirper/vendor"
    ports:
      - 3000:8000

  chirper_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
        - chirper_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  chirper_db_data:
    driver: local